[package]
name = "sct"
version = "0.6.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
description = "Certificate transparency SCT verification library"
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
homepage = "https://github.com/ctz/sct.rs"
repository = "https://github.com/ctz/sct.rs"
categories = ["network-programming", "cryptography"]

[dependencies]
ring = { git="https://github.com/jyao1/ring", branch="uefi_support"}
untrusted = "0.7.0"
